on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-18.04,   r: 'devel'}
          
   steps:
      - run: |
          git clone https://github.com/jimhester/testUnload.git
      
      - run: |
          install.packages("testUnload", repos = NULL, type = "source")
          library("testUnload")
          unloadNamespace("testUnload")
          install.packages("testUnload", repos = NULL, type = "source")
          library("testUnload")
        shell: Rscript {0}
